# Generated by Django 5.0.6 on 2024-07-01 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
